# Generated by Django 6.0.5 on 2026-05-28 08:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dipendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('reparto', models.CharField(blank=True, max_length=100)),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Dipendenti',
                'ordering': ['cognome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sito_web', models.URLField(blank=True)),
                ('contatto_email', models.EmailField(blank=True, max_length=254)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Vendor',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Corso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=300)),
                ('descrizione', models.TextField(blank=True)),
                ('durata_ore', models.PositiveIntegerField(default=0)),
                ('validita_mesi', models.PositiveIntegerField(default=0, help_text='0 = nessuna scadenza')),
                ('obbligatorio', models.BooleanField(default=False)),
                ('link_corso', models.URLField(blank=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corsi', to='gestionale.vendor')),
            ],
            options={
                'verbose_name_plural': 'Corsi',
                'ordering': ['titolo'],
            },
        ),
        migrations.CreateModel(
            name='AssegnazioneCorso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_assegnazione', models.DateField(default=django.utils.timezone.now)),
                ('data_scadenza', models.DateField(blank=True, null=True)),
                ('data_completamento', models.DateField(blank=True, null=True)),
                ('stato', models.CharField(choices=[('da_completare', 'Da completare'), ('in_corso', 'In corso'), ('completato', 'Completato'), ('scaduto', 'Scaduto')], default='da_completare', max_length=20)),
                ('data_inizio_pianificata', models.DateField(blank=True, null=True)),
                ('data_fine_pianificata', models.DateField(blank=True, null=True)),
                ('certificato', models.FileField(blank=True, null=True, upload_to='certificati/')),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assegnazioni', to='gestionale.corso')),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assegnazioni', to='gestionale.dipendente')),
            ],
            options={
                'verbose_name': 'Assegnazione Corso',
                'verbose_name_plural': 'Assegnazioni Corsi',
                'ordering': ['data_scadenza'],
                'unique_together': {('dipendente', 'corso')},
            },
        ),
    ]
