# Generated by Django 6.0.5 on 2026-06-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0005_add_timestamps_and_fix_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='dipendente',
            name='stipendio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Stipendio mensile (€)'),
        ),
    ]
